// GENERATED by tools/mathc.py from fonts/Euler-Math.otf. Do not edit.
// The math font manifest (plan P1-23): paint (shell.mjs installs it as a
// declared webfont with role 'math'), static export and packaging read it.
export const MATH_FONT = { family: 'Euler Math', file: 'fonts/euler-math.woff2', hash: 'b8a46ff5bb595211', role: 'math' };
