// GENERATED from engine/data/math/symbols.tsv by tools/mathdict.py — do not edit.
// name → [code point, class] for tools (converters, the editor).
export const MATH_SYMBOLS = {
  "*": [0x2217, "bin"],
  "+": [0x2B, "bin"],
  "+-": [0xB1, "bin"],
  ",": [0x2C, "punct"],
  "-": [0x2212, "bin"],
  "-+": [0x2213, "bin"],
  "-->": [0x27F6, "rel"],
  "--|": [0x22A3, "rel"],
  "-=": [0x2261, "rel"],
  "->": [0x2192, "rel"],
  "...": [0x2026, "ord"],
  ":": [0x2236, "rel"],
  ":.": [0x2234, "ord"],
  "::=": [0x2A74, "rel"],
  ":=": [0x2254, "rel"],
  ";": [0x3B, "punct"],
  "<": [0x3C, "rel"],
  "<-": [0x2190, "rel"],
  "<--": [0x27F5, "rel"],
  "<->": [0x2194, "rel"],
  "<<": [0x226A, "rel"],
  "<=": [0x2264, "rel"],
  "<==": [0x27F8, "rel"],
  "<=>": [0x21D4, "rel"],
  "=": [0x3D, "rel"],
  "=:": [0x2255, "rel"],
  "==>": [0x27F9, "rel"],
  "=>": [0x21D2, "rel"],
  ">": [0x3E, "rel"],
  ">=": [0x2265, "rel"],
  ">>": [0x226B, "rel"],
  "AA": [0x1D538, "ord"],
  "BB": [0x1D539, "ord"],
  "CC": [0x2102, "ord"],
  "DD": [0x1D53B, "ord"],
  "Delta": [0x394, "ord"],
  "Downarrow": [0x21D3, "rel"],
  "EE": [0x1D53C, "ord"],
  "FF": [0x1D53D, "ord"],
  "GG": [0x1D53E, "ord"],
  "Gamma": [0x393, "ord"],
  "HH": [0x210D, "ord"],
  "II": [0x1D540, "ord"],
  "Im": [0x2111, "ord"],
  "JJ": [0x1D541, "ord"],
  "KK": [0x1D542, "ord"],
  "LL": [0x1D543, "ord"],
  "Lambda": [0x39B, "ord"],
  "MM": [0x1D544, "ord"],
  "NN": [0x2115, "ord"],
  "OO": [0x1D546, "ord"],
  "Omega": [0x3A9, "ord"],
  "PP": [0x2119, "ord"],
  "Phi": [0x3A6, "ord"],
  "Pi": [0x3A0, "ord"],
  "Pr": [0x0, "op"],
  "Psi": [0x3A8, "ord"],
  "QQ": [0x211A, "ord"],
  "RR": [0x211D, "ord"],
  "Re": [0x211C, "ord"],
  "SS": [0x1D54A, "ord"],
  "Sigma": [0x3A3, "ord"],
  "TT": [0x1D54B, "ord"],
  "Theta": [0x398, "ord"],
  "UU": [0x1D54C, "ord"],
  "Uparrow": [0x21D1, "rel"],
  "Updownarrow": [0x21D5, "rel"],
  "Upsilon": [0x3A5, "ord"],
  "VV": [0x1D54D, "ord"],
  "WW": [0x1D54E, "ord"],
  "XX": [0x1D54F, "ord"],
  "Xi": [0x39E, "ord"],
  "YY": [0x1D550, "ord"],
  "ZZ": [0x2124, "ord"],
  "aleph": [0x2135, "ord"],
  "alpha": [0x3B1, "ord"],
  "amalg": [0x2A3F, "bin"],
  "angle": [0x2220, "ord"],
  "approx": [0x2248, "rel"],
  "arccos": [0x0, "op"],
  "arcsin": [0x0, "op"],
  "arctan": [0x0, "op"],
  "arg": [0x0, "op"],
  "argmax": [0x0, "op"],
  "argmin": [0x0, "op"],
  "ast": [0x2217, "bin"],
  "because": [0x2235, "ord"],
  "beta": [0x3B2, "ord"],
  "bigcap": [0x22C2, "op"],
  "bigcup": [0x22C3, "op"],
  "bigodot": [0x2A00, "op"],
  "bigoplus": [0x2A01, "op"],
  "bigotimes": [0x2A02, "op"],
  "bigsqcup": [0x2A06, "op"],
  "biguplus": [0x2A04, "op"],
  "bigvee": [0x22C1, "op"],
  "bigwedge": [0x22C0, "op"],
  "bot": [0x22A5, "ord"],
  "bullet": [0x2219, "bin"],
  "cap": [0x2229, "bin"],
  "cdot": [0x22C5, "bin"],
  "cdots": [0x22EF, "ord"],
  "chi": [0x3C7, "ord"],
  "circ": [0x2218, "bin"],
  "cong": [0x2245, "rel"],
  "coprod": [0x2210, "op"],
  "cos": [0x0, "op"],
  "cosh": [0x0, "op"],
  "cot": [0x0, "op"],
  "coth": [0x0, "op"],
  "csc": [0x0, "op"],
  "cup": [0x222A, "bin"],
  "dashv": [0x22A3, "rel"],
  "ddots": [0x22F1, "ord"],
  "deg": [0x0, "op"],
  "degree": [0xB0, "ord"],
  "delta": [0x3B4, "ord"],
  "det": [0x0, "op"],
  "dim": [0x0, "op"],
  "div": [0xF7, "bin"],
  "downarrow": [0x2193, "rel"],
  "ell": [0x2113, "ord"],
  "empty": [0x2205, "ord"],
  "emptyset": [0x2205, "ord"],
  "epsilon": [0x3B5, "ord"],
  "equiv": [0x2261, "rel"],
  "eta": [0x3B7, "ord"],
  "exists": [0x2203, "ord"],
  "exp": [0x0, "op"],
  "forall": [0x2200, "ord"],
  "gamma": [0x3B3, "ord"],
  "gcd": [0x0, "op"],
  "geq": [0x2265, "rel"],
  "gets": [0x2190, "rel"],
  "gg": [0x226B, "rel"],
  "grad": [0x2207, "ord"],
  "hbar": [0x210F, "ord"],
  "hom": [0x0, "op"],
  "hookleftarrow": [0x21A9, "rel"],
  "hookrightarrow": [0x21AA, "rel"],
  "iiint": [0x222D, "op"],
  "iint": [0x222C, "op"],
  "in": [0x2208, "rel"],
  "inf": [0x0, "op"],
  "infinity": [0x221E, "ord"],
  "infty": [0x221E, "ord"],
  "int": [0x222B, "op"],
  "iota": [0x3B9, "ord"],
  "kappa": [0x3BA, "ord"],
  "ker": [0x0, "op"],
  "lambda": [0x3BB, "ord"],
  "langle": [0x27E8, "open"],
  "lceil": [0x2308, "open"],
  "ldots": [0x2026, "ord"],
  "leftharpoonup": [0x21BC, "rel"],
  "leftrightarrows": [0x21C6, "rel"],
  "leq": [0x2264, "rel"],
  "lfloor": [0x230A, "open"],
  "lg": [0x0, "op"],
  "lim": [0x0, "op"],
  "liminf": [0x0, "op"],
  "limsup": [0x0, "op"],
  "ll": [0x226A, "rel"],
  "ln": [0x0, "op"],
  "log": [0x0, "op"],
  "mapsto": [0x21A6, "rel"],
  "max": [0x0, "op"],
  "mid": [0x2223, "rel"],
  "min": [0x0, "op"],
  "mod": [0x0, "op"],
  "models": [0x22A8, "rel"],
  "mp": [0x2213, "bin"],
  "mu": [0x3BC, "ord"],
  "nabla": [0x2207, "ord"],
  "nearrow": [0x2197, "rel"],
  "neg": [0xAC, "ord"],
  "neq": [0x2260, "rel"],
  "nexists": [0x2204, "ord"],
  "ni": [0x220B, "rel"],
  "not": [0xAC, "ord"],
  "notin": [0x2209, "rel"],
  "nu": [0x3BD, "ord"],
  "nwarrow": [0x2196, "rel"],
  "odot": [0x2299, "bin"],
  "oint": [0x222E, "op"],
  "omega": [0x3C9, "ord"],
  "omicron": [0x3BF, "ord"],
  "ominus": [0x2296, "bin"],
  "oo": [0x221E, "ord"],
  "oplus": [0x2295, "bin"],
  "oslash": [0x2298, "bin"],
  "otimes": [0x2297, "bin"],
  "ox": [0x2297, "bin"],
  "parallel": [0x2225, "rel"],
  "partial": [0x2202, "ord"],
  "perp": [0x22A5, "rel"],
  "phi": [0x3C6, "ord"],
  "pi": [0x3C0, "ord"],
  "pm": [0xB1, "bin"],
  "prec": [0x227A, "rel"],
  "preceq": [0x2AAF, "rel"],
  "prime": [0x2032, "ord"],
  "prod": [0x220F, "op"],
  "prop": [0x221D, "rel"],
  "propto": [0x221D, "rel"],
  "psi": [0x3C8, "ord"],
  "rangle": [0x27E9, "close"],
  "rceil": [0x2309, "close"],
  "rfloor": [0x230B, "close"],
  "rho": [0x3C1, "ord"],
  "rightharpoonup": [0x21C0, "rel"],
  "rightleftharpoons": [0x21CC, "rel"],
  "searrow": [0x2198, "rel"],
  "sec": [0x0, "op"],
  "setminus": [0x2216, "bin"],
  "sigma": [0x3C3, "ord"],
  "sim": [0x223C, "rel"],
  "simeq": [0x2243, "rel"],
  "sin": [0x0, "op"],
  "sinh": [0x0, "op"],
  "sqcap": [0x2293, "bin"],
  "sqcup": [0x2294, "bin"],
  "sqsubseteq": [0x2291, "rel"],
  "sqsupseteq": [0x2292, "rel"],
  "square": [0x25A1, "ord"],
  "star": [0x22C6, "bin"],
  "subset": [0x2282, "rel"],
  "subseteq": [0x2286, "rel"],
  "succ": [0x227B, "rel"],
  "succeq": [0x2AB0, "rel"],
  "sum": [0x2211, "op"],
  "sup": [0x0, "op"],
  "supset": [0x2283, "rel"],
  "supseteq": [0x2287, "rel"],
  "swarrow": [0x2199, "rel"],
  "tan": [0x0, "op"],
  "tanh": [0x0, "op"],
  "tau": [0x3C4, "ord"],
  "therefore": [0x2234, "ord"],
  "theta": [0x3B8, "ord"],
  "times": [0xD7, "bin"],
  "to": [0x2192, "rel"],
  "top": [0x22A4, "ord"],
  "triangle": [0x25B3, "ord"],
  "uparrow": [0x2191, "rel"],
  "updownarrow": [0x2195, "rel"],
  "uplus": [0x228E, "bin"],
  "upsilon": [0x3C5, "ord"],
  "varepsilon": [0x3F5, "ord"],
  "varphi": [0x3D5, "ord"],
  "varpi": [0x3D6, "ord"],
  "varrho": [0x3F1, "ord"],
  "varsigma": [0x3C2, "ord"],
  "vartheta": [0x3D1, "ord"],
  "vdash": [0x22A2, "rel"],
  "vdots": [0x22EE, "ord"],
  "vee": [0x2228, "bin"],
  "wedge": [0x2227, "bin"],
  "wp": [0x2118, "ord"],
  "xi": [0x3BE, "ord"],
  "xx": [0xD7, "bin"],
  "zeta": [0x3B6, "ord"],
  "|": [0x7C, "ord"],
  "|-": [0x22A2, "rel"],
  "|--": [0x22A2, "rel"],
  "|-->": [0x27FC, "rel"],
  "|->": [0x21A6, "rel"],
  "|=": [0x22A8, "rel"],
  "|==": [0x22A8, "rel"],
  "||": [0x2016, "ord"],
  "~": [0x223C, "rel"],
  "~=": [0x2245, "rel"],
  "~>": [0x21DD, "rel"],
  "~~": [0x2248, "rel"],
};

// TeX command (no backslash) → its spelling here (plan P3-24: the converters' one map)
export const TEX_MATH = {
  "Delta": "Delta",
  "Downarrow": "Downarrow",
  "Gamma": "Gamma",
  "Im": "Im",
  "Lambda": "Lambda",
  "Leftrightarrow": "<=>",
  "Longleftarrow": "<==",
  "Longrightarrow": "==>",
  "Omega": "Omega",
  "Phi": "Phi",
  "Pi": "Pi",
  "Pr": "Pr",
  "Psi": "Psi",
  "Re": "Re",
  "Rightarrow": "=>",
  "Sigma": "Sigma",
  "Theta": "Theta",
  "Uparrow": "Uparrow",
  "Updownarrow": "Updownarrow",
  "Upsilon": "Upsilon",
  "Vert": "||",
  "Xi": "Xi",
  "aleph": "aleph",
  "alpha": "alpha",
  "amalg": "amalg",
  "angle": "angle",
  "approx": "approx",
  "arccos": "arccos",
  "arcsin": "arcsin",
  "arctan": "arctan",
  "arg": "arg",
  "argmax": "argmax",
  "argmin": "argmin",
  "ast": "ast",
  "because": "because",
  "beta": "beta",
  "bigcap": "bigcap",
  "bigcup": "bigcup",
  "bigodot": "bigodot",
  "bigoplus": "bigoplus",
  "bigotimes": "bigotimes",
  "bigsqcup": "bigsqcup",
  "biguplus": "biguplus",
  "bigvee": "bigvee",
  "bigwedge": "bigwedge",
  "bot": "bot",
  "bullet": "bullet",
  "cap": "cap",
  "cdot": "cdot",
  "cdots": "cdots",
  "chi": "chi",
  "circ": "circ",
  "coloneqq": ":=",
  "cong": "cong",
  "coprod": "coprod",
  "cos": "cos",
  "cosh": "cosh",
  "cot": "cot",
  "coth": "coth",
  "csc": "csc",
  "cup": "cup",
  "dashv": "dashv",
  "ddots": "ddots",
  "deg": "deg",
  "degree": "degree",
  "delta": "delta",
  "det": "det",
  "dim": "dim",
  "div": "div",
  "dots": "...",
  "downarrow": "downarrow",
  "ell": "ell",
  "empty": "empty",
  "emptyset": "emptyset",
  "epsilon": "epsilon",
  "eqqcolon": "=:",
  "equiv": "equiv",
  "eta": "eta",
  "exists": "exists",
  "exp": "exp",
  "forall": "forall",
  "gamma": "gamma",
  "gcd": "gcd",
  "ge": ">=",
  "geq": ">=",
  "gets": "<-",
  "gg": ">>",
  "grad": "grad",
  "hbar": "hbar",
  "hom": "hom",
  "hookleftarrow": "hookleftarrow",
  "hookrightarrow": "hookrightarrow",
  "iff": "<=>",
  "iiint": "iiint",
  "iint": "iint",
  "implies": "=>",
  "in": "in",
  "inf": "inf",
  "infinity": "infinity",
  "infty": "infty",
  "int": "int",
  "iota": "iota",
  "kappa": "kappa",
  "ker": "ker",
  "lambda": "lambda",
  "langle": "langle",
  "lceil": "lceil",
  "ldots": "...",
  "le": "<=",
  "leftarrow": "<-",
  "leftharpoonup": "leftharpoonup",
  "leftrightarrow": "<->",
  "leftrightarrows": "leftrightarrows",
  "leq": "<=",
  "lfloor": "lfloor",
  "lg": "lg",
  "lim": "lim",
  "liminf": "liminf",
  "limsup": "limsup",
  "ll": "<<",
  "ln": "ln",
  "log": "log",
  "longleftarrow": "<--",
  "longrightarrow": "-->",
  "mapsto": "mapsto",
  "max": "max",
  "mid": "mid",
  "min": "min",
  "mod": "mod",
  "models": "models",
  "mp": "-+",
  "mu": "mu",
  "nRightarrow": "!=>",
  "nabla": "nabla",
  "ncong": "!cong",
  "ne": "!=",
  "nearrow": "nearrow",
  "neg": "neg",
  "neq": "neq",
  "nexists": "nexists",
  "ngeq": "!>=",
  "ngtr": "!>",
  "ni": "ni",
  "nleftarrow": "!<-",
  "nleq": "!<=",
  "nless": "!<",
  "nmid": "!mid",
  "not": "not",
  "notin": "notin",
  "nparallel": "!parallel",
  "nrightarrow": "!->",
  "nsim": "!sim",
  "nsubseteq": "!subseteq",
  "nsupseteq": "!supseteq",
  "nu": "nu",
  "nwarrow": "nwarrow",
  "odot": "odot",
  "oint": "oint",
  "omega": "omega",
  "omicron": "omicron",
  "ominus": "ominus",
  "oo": "oo",
  "oplus": "oplus",
  "oslash": "oslash",
  "otimes": "otimes",
  "ox": "ox",
  "parallel": "parallel",
  "partial": "partial",
  "perp": "perp",
  "phi": "phi",
  "pi": "pi",
  "pm": "+-",
  "prec": "prec",
  "preceq": "preceq",
  "prime": "prime",
  "prod": "prod",
  "prop": "prop",
  "propto": "propto",
  "psi": "psi",
  "rangle": "rangle",
  "rceil": "rceil",
  "rfloor": "rfloor",
  "rho": "rho",
  "rightarrow": "->",
  "rightharpoonup": "rightharpoonup",
  "rightleftharpoons": "rightleftharpoons",
  "searrow": "searrow",
  "sec": "sec",
  "setminus": "setminus",
  "sigma": "sigma",
  "sim": "sim",
  "simeq": "simeq",
  "sin": "sin",
  "sinh": "sinh",
  "sqcap": "sqcap",
  "sqcup": "sqcup",
  "sqsubseteq": "sqsubseteq",
  "sqsupseteq": "sqsupseteq",
  "square": "square",
  "star": "star",
  "subset": "subset",
  "subseteq": "subseteq",
  "succ": "succ",
  "succeq": "succeq",
  "sum": "sum",
  "sup": "sup",
  "supset": "supset",
  "supseteq": "supseteq",
  "swarrow": "swarrow",
  "tan": "tan",
  "tanh": "tanh",
  "tau": "tau",
  "therefore": "therefore",
  "theta": "theta",
  "times": "times",
  "to": "->",
  "top": "top",
  "triangle": "triangle",
  "uparrow": "uparrow",
  "updownarrow": "updownarrow",
  "uplus": "uplus",
  "upsilon": "upsilon",
  "varepsilon": "varepsilon",
  "varphi": "varphi",
  "varpi": "varpi",
  "varrho": "varrho",
  "varsigma": "varsigma",
  "vartheta": "vartheta",
  "vdash": "vdash",
  "vdots": "vdots",
  "vee": "vee",
  "vert": "|",
  "wedge": "wedge",
  "wp": "wp",
  "xi": "xi",
  "xx": "xx",
  "zeta": "zeta",
};
// the math alphabets' row names (\mathbb → bb, …)
export const MATH_ALPHABETS = ["bb", "cal", "frak", "bold", "italic", "sans", "mono"];
