#!/usr/bin/env node
// Hyphenation dictionaries (plan P4-06; D-X09) from the `hyphen` npm
// package's Liang patterns, as TeX pattern text — the one form the engine
// compiles (engine/src/hyphen/hyphen.cc), whoever supplies it:
// - engine/gen/hyphen_en_us.h: en-US, resident (compiled in);
// - test/hyph: the golden provider's German (de-1996) and its index.json,
//   committed — the native runner, tsrc and wasm-goldens answer
//   hyphPatterns from it;
// - with --assets, runtime/assets/hyph/<tag>.json for every language and
//   index.json (BCP-47 tag → file): what the browser runtime's
//   hyphPatterns provider serves (gitignored, like the hl assets);
// - test/golden/hyphen/words.txt: a truth golden from the npm
//   implementation itself.
// A dictionary file: {tag, leftmin, rightmin, hyphenChar, patterns,
// exceptions} — patterns as TeX writes them (".ach4 a1b …"), exceptions as
// hyphenated words ("as-so-ciate …").
import { createRequire } from 'node:module';
import { writeFileSync, mkdirSync, readdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const root = join(dirname(fileURLToPath(import.meta.url)), '..');

// the package's compiled trie back to TeX patterns: a trie path whose node
// names a levels row is a pattern; a row's levels stand before each of its
// letters and after the last (a pattern that starts with '.': after the dot)
export function dictionary(tag) {
  const [levels, trie, exceptions] = require(`hyphen/patterns/${tag}`);
  const patterns = [];
  const walk = (node, prefix) => {
    for (const key of Object.keys(node).sort()) {
      const v = node[key];
      let child = null, row = -1;
      if (typeof v === 'number') row = v;
      else if (Array.isArray(v)) [child, row] = v;
      else child = v;
      const path = prefix + key;
      if (row >= 0) {
        const dot = path[0] === '.';
        const letters = [...path].slice(dot ? 1 : 0), lv = levels[row];
        let t = dot ? '.' : '';
        letters.forEach((c, i) => {
          if (lv[i]) t += lv[i];
          t += c;
        });
        if (lv[letters.length]) t += lv[letters.length];
        patterns.push(t);
      }
      if (child) walk(child, path);
    }
  };
  walk(trie, '');
  const exc = Object.keys(exceptions ?? {}).sort().map((w) => {
    const marks = new Set(exceptions[w]);
    return [...w].map((c, i) => (marks.has(i) ? '-' : '') + c).join('');
  });
  // (the package's own minima: two letters on either side)
  return { tag, leftmin: 2, rightmin: 2, hyphenChar: '-', patterns: patterns.join(' '), exceptions: exc.join(' ') };
}

const write = (rel, text) => {
  const dest = join(root, rel);
  mkdirSync(dirname(dest), { recursive: true });
  writeFileSync(dest, text);
  return dest;
};

// the resident dictionary: its pattern text, compiled once on first use
const en = dictionary('en-us');
write('engine/gen/hyphen_en_us.h', `// GENERATED by tools/hyphc.mjs from the 'hyphen' npm package (en-US TeX
// patterns) — do not edit. The resident dictionary (plan P4-06; D-X09):
// engine/src/hyphen/hyphen.cc compiles it on first use.
#pragma once
namespace tsr { namespace hyphen_en_us {
inline constexpr const char* kTag = "en-US";
inline constexpr unsigned char kLeftmin = ${en.leftmin}, kRightmin = ${en.rightmin};
inline constexpr const char* kHyphenChar = "${en.hyphenChar}";
inline constexpr const char* kPatterns =
${en.patterns.match(/.{1,96}(\s|$)/g).map((l) => `    "${l}"`).join('\n')};
inline constexpr const char* kExceptions = "${en.exceptions}";
} }  // namespace tsr::hyphen_en_us
`);
console.log(`wrote engine/gen/hyphen_en_us.h: ${en.patterns.split(' ').length} patterns`);

// the golden provider's German (its index as the runtime's)
write('test/hyph/de-1996.json', JSON.stringify(dictionary('de-1996')) + '\n');
write('test/hyph/index.json', JSON.stringify({ de: 'de-1996', 'de-1996': 'de-1996' }, null, 1) + '\n');

// --assets: every language the package has, and the tags that name them
if (process.argv.includes('--assets')) {
  const dir = 'runtime/assets/hyph';
  const tags = readdirSync(join(root, 'node_modules/hyphen/patterns')).map((f) => f.replace(/\.js$/, '')).sort();
  const index = {};
  for (const tag of tags) {
    let d;
    try {
      d = dictionary(tag);
    } catch {
      console.log(`skipped ${tag} (the package's file does not load)`);
      continue;
    }
    write(`${dir}/${tag}.json`, JSON.stringify(d) + '\n');
    index[tag] = tag;
  }
  // a language's default orthography (BCP-47 tags without the variant)
  const DEFAULTS = { de: 'de-1996', 'de-ch': 'de-ch-1901', en: 'en-us', el: 'el-monoton', mn: 'mn-cyrl',
                     sr: 'sr-cyrl', sh: 'sh-latn', 'sr-latn': 'sh-latn', 'sr-cyrl': 'sr-cyrl' };
  for (const [tag, file] of Object.entries(DEFAULTS)) if (index[file]) index[tag] = file;
  write(`${dir}/index.json`, JSON.stringify(index, null, 1) + '\n');
  console.log(`wrote ${dir}: ${Object.keys(index).length} tags`);
}

// the truth golden, by the npm implementation
const { hyphenateSync } = require('hyphen/en-us');
const words = [
  'hyphenation', 'typesetting', 'paragraph', 'algorithm', 'beautiful',
  'representation', 'demonstration', 'university', 'extraordinary',
  'measurement', 'associate', 'declination', 'philanthropic', 'present',
  'interword', 'spacing', 'optimal', 'quantization', 'justification',
  'engineering', 'wonderful', 'chairs', 'table', 'documentation',
];
write('test/golden/hyphen/words.txt', words.map((w) => `${w} ${hyphenateSync(w).split('­').join('-')}`).join('\n') + '\n');
