#!/usr/bin/env node
// Compiles the `hyphen` npm package's en-US Liang patterns into a compact
// C++ header (engine/gen/hyphen_en_us.h) + a truth golden generated with the
// npm implementation itself (test/golden/hyphen/words.txt).
import { createRequire } from 'node:module';
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const [levelsTable, trie, exceptions] = require('hyphen/patterns/en-us');

// --- flatten levels table ---
const levelData = [];
const levelOff = [0];
for (const pat of levelsTable) {
  for (const v of pat) levelData.push(v);
  levelOff.push(levelData.length);
}

// --- flatten trie (node value forms: Object | [Object, idx] | Number) ---
const nodePattern = [];
const nodeEdges = [];  // per node: [char, childId][]
function addNode(obj) {
  const id = nodePattern.length;
  nodePattern.push(-1);
  nodeEdges.push([]);
  for (const key of Object.keys(obj).sort()) {
    const v = obj[key];
    let childObj = null, patIdx = -1;
    if (typeof v === 'number') patIdx = v;
    else if (Array.isArray(v)) { childObj = v[0]; patIdx = v[1]; }
    else childObj = v;
    const child = addNode(childObj ?? {});
    if (patIdx >= 0) nodePattern[child] = patIdx;
    nodeEdges[id].push([key, child]);
  }
  return id;
}
addNode(trie);  // node 0 = root

const edgeChar = [], edgeChild = [], nodeEdgeStart = [0];
for (const edges of nodeEdges) {
  for (const [c, child] of edges) {
    edgeChar.push(c.charCodeAt(0));
    edgeChild.push(child);
  }
  nodeEdgeStart.push(edgeChar.length);
}

// --- exceptions ---
const excWords = Object.keys(exceptions ?? {}).sort();
const excMarkerData = [], excMarkerOff = [0];
for (const w of excWords) {
  for (const m of exceptions[w]) excMarkerData.push(m);
  excMarkerOff.push(excMarkerData.length);
}

const fmt = (arr, perLine = 24) => {
  let s = '';
  for (let i = 0; i < arr.length; i += perLine)
    s += '  ' + arr.slice(i, i + perLine).join(',') + ',\n';
  return s;
};

const header = `// GENERATED by tools/hyphc.mjs from the 'hyphen' npm package (en-US
// TeX patterns, Liang's algorithm). Do not edit.
#pragma once
#include <cstdint>
namespace tsr { namespace hyphen_en_us {
inline constexpr int kNodeCount = ${nodePattern.length};
inline constexpr uint8_t kLevelData[] = {
${fmt(levelData)}};
inline constexpr uint16_t kLevelOff[] = {
${fmt(levelOff)}};
inline constexpr int32_t kNodePattern[] = {
${fmt(nodePattern)}};
inline constexpr uint32_t kNodeEdgeStart[] = {
${fmt(nodeEdgeStart)}};
inline constexpr uint8_t kEdgeChar[] = {
${fmt(edgeChar)}};
inline constexpr uint32_t kEdgeChild[] = {
${fmt(edgeChild)}};
inline constexpr int kExcCount = ${excWords.length};
inline constexpr const char* kExcWords[] = {
${excWords.map((w) => `  "${w}",`).join('\n')}
};
inline constexpr uint8_t kExcMarkerData[] = {
${fmt(excMarkerData)}};
inline constexpr uint16_t kExcMarkerOff[] = {
${fmt(excMarkerOff)}};
} }  // namespace tsr::hyphen_en_us
`;

const dest = join(root, 'engine/gen/hyphen_en_us.h');
mkdirSync(dirname(dest), { recursive: true });
writeFileSync(dest, header);
console.log(`wrote ${dest}: ${nodePattern.length} nodes, ${edgeChar.length} edges, ${excWords.length} exceptions`);

// --- truth golden via the npm implementation ---
const { hyphenateSync } = require('hyphen/en-us');
const words = [
  'hyphenation', 'typesetting', 'paragraph', 'algorithm', 'beautiful',
  'representation', 'demonstration', 'university', 'extraordinary',
  'measurement', 'associate', 'declination', 'philanthropic', 'present',
  'interword', 'spacing', 'optimal', 'quantization', 'justification',
  'engineering', 'wonderful', 'chairs', 'table', 'documentation',
];
const lines = words.map((w) => `${w} ${hyphenateSync(w).split('­').join('-')}`);
const goldenDest = join(root, 'test/golden/hyphen/words.txt');
mkdirSync(dirname(goldenDest), { recursive: true });
writeFileSync(goldenDest, lines.join('\n') + '\n');
console.log(`wrote ${goldenDest} (${words.length} words)`);
